### ISSUE TITLE
Ordering of assets doesn't work in grails 2.3.8

### ISSUE THREAD

**Issue by PatrickHuetter** [bertramdev/grails-asset-pipeline#102]
I have a special ordering in my assets:

```
//= require core
//= require jqueryValidate
//= require ../theme/assets/scripts/login
//= require_self

.... javascript code
```

In the generated/compiled js file the javascript code is on top of the file, not in the bottom.

**Comment by biniama** [comment]
Hello. Did you find the solution for this?
