### ISSUE TITLE
Debugging asset pipeline in production !

### ISSUE THREAD

**Issue by snimavat** [bertramdev/grails-asset-pipeline#166]
Is there any similar option as grails.resources.debug = true or parameter _debugResources=y in resources plugin.

What I am looking for is, disable every thing but dependency management, to help identify / debug problems in production.

In production, asset pipeline would bundle everything, rename file with hashes. I dont find any thing in document that mention how to disable assetpipline in production and still have dependency management,

**Comment by aleksz** [comment]
Exactly same issue here. Do you need any information to handle issue? :)

**Comment by abobwhite** [comment]
@davydotcom Could this issue be re-opened?

**Comment by snimavat** [comment]
@davydotcom Any updates on how to get sourcemaps working with latest release ?

**Comment by splix** [comment]
Same issue, `grails.assets.enableSourceMaps = true` doesn't work

**Comment by davydotcom** [comment]
^ what grails version

**Comment by splix** [comment]
2.4.4

**Comment by davydotcom** [comment]
just to be clear source maps only work for javascript atm with minifyJs turned on, your not seeing the un minified js?

**Comment by abobwhite** [comment]
No. As stated above this has been a problem for a long time.

**Comment by splix** [comment]
minifyJs is enabled, but I don't get any sourcemap files, only minified js

**Comment by davydotcom** [comment]
This should be working now in 2.3.0 release
