### ISSUE TITLE
'File was not sourced' error occurred when running on server

### ISSUE THREAD

**Issue by kyle306** [bertramdev/grails-asset-pipeline#191]
Hi,
When the Jenkins job runs on my Ubuntu server with JDK 7, it always says the following error.  The weird thing is the same grails command works fine on my Mac for the same project.  Even after disabling the minify for JS and CSS, the error is still there. '/grails-app/assets/javascripts' is not a available folder in the project.

Do you have any idea about that?

--------- Log starts -------------
[workspace] $ /home/twer/.jenkins/jobs/Budget/workspace/grailsw -Dgrails.work.dir=/home/twer/.jenkins/jobs/Budget/workspace//target war --non-interactive --plain-output

|Loading Grails 2.4.4

|Configuring classpath

.
|Environment set to production

.................................
|Packaging Grails application

...........................................
|Compiling 7 GSP files for package [budget]

..
|Compiling 4 GSP files for package [databaseMigration]

..
|Building WAR file

................................................................................
|Precompiling Assets!

|Processing File 1 of 242 - searchAccountCtrl.js
|Compressing File 1 of 242 - searchAccountCtrl
|Processing File 2 of 242 - searchAccountService.js
|Compressing File 2 of 242 - searchAccountService
|Processing File 3 of 242 - application.js
.Error 
|
WAR packaging error: File was not sourced from the same ScanDirectory /home/twer/.jenkins/jobs/Budget/workspace/grails-app/assets/components/angular/angular.min.js scanDir: /home/twer/.jenkins/jobs/Budget/workspace/grails-app/assets/javascripts
Build step 'Build With Grails' marked build as failure
Archiving artifacts
Finished: FAILURE
--------- Log ends -------------

--------- Plugins starts ---------------
plugins {
        // plugins for the build system only
        build ":tomcat:7.0.55"

```
    // plugins for the compile step
    compile ":scaffolding:2.1.2"
    compile ':cache:1.1.8'
    compile ":asset-pipeline:2.0.19"
    compile ":quartz:1.0.2"
    compile ":less-asset-pipeline:2.0.8"

    // plugins needed at runtime but not for compilation
    runtime ":hibernate4:4.3.6.1"
    runtime ":database-migration:1.4.0"
    runtime ":jquery:1.11.1"
    runtime ':twitter-bootstrap:3.3.1'
}
```

--------- Plugins ends ---------------

**Comment by neoecos** [comment]
Hi, i was having the same issue using the @import statement whithin .less files

Just have to remove the relative path, to use an absoluth path relative to the assets folder

**Comment by delor34n** [comment]
hey - so someone is having issues on linux?

**Comment by neoecos** [comment]
@delor34n, try what i mentioned before. To me it works.

**Comment by delor34n** [comment]
Well, I really hope that you can help with this. I've tried everything but I'm having this exception:

```groovy
| Precompiling Assets!
Cache [:]
Cache [:]
Cache [:]
| Processing File 1 of 406 - app.scss
    error /app.scss (asset.pipeline.fs.FileSystemAssetResolver.relativePathToResolver(FileSystemAssetResolver.groovy:163): File was not sourced from the same ScanDirectory /home/delor34n/_voyhoy/lab-grails-app/grails-app/assets/bower_components/foundation/scss/foundation/_functions.scss scanDir: /home/delor34n/_voyhoy/lab-grails| Processing File 1 of 406 - app.scss.
| Error WAR packaging error: File was not sourced from the same ScanDirectory /home/delor34n/_voyhoy/lab-grails-app/grails-app/assets/bower_components/foundation/scss/foundation/_functions.scss scanDir: /home/delor34n/_voyhoy/lab-grails-app/grails-app/assets/stylesheets
```
I have two files with the imports. The first one is `_settings.scss`:

```
@import "../bower_components/foundation/scss/foundation/functions";
```
and the second one `app.scss`
```scss
/* Vendor */
@import "scss/vendor/font-awesome";
@import "scss/vendor/jquery-ui";

/* Foundation */
@import "settings";

@import
"../bower_components/foundation/scss/foundation/components/forms",
"../bower_components/foundation/scss/foundation/components/grid",
"../bower_components/foundation/scss/foundation/components/inline-lists",
...
...
```

This configuration its working on OSX laptops, but I'm using a linux distro (Ubuntu 14.04). I've tried setting the absolute path to `the bower_components` but threw me a bigger exception.

**Comment by nithin2e** [comment]
try 
@import
"foundation/scss/foundation/components/forms",
"foundation/scss/foundation/components/grid",
"foundation/scss/foundation/components/inline-lists" 

worked for me this way

**Comment by davydotcom** [comment]
Looking at the error looks like scanDir is off not sure why its set to lab-grails

**Comment by davydotcom** [comment]
aha actually it is right. @nithin2e is correct. you are trying to traverse an organizational directory path. Remember the top level subdirectories of the `assets` folder is flattened. This error is there to keep the resolvers from allowing you to traverse outside of your projects registered asset path as a security layer. Reference the files as if its on the same directory level as your stylesheets folder.

**Comment by davydotcom** [comment]
P.S. the reason it might work on OS X vs linux is the sass plugin uses compass and has a filesystem fallback if it cant resolve the asset from within the asset-pipeline resolvers.
