### ISSUE TITLE
Where can I find documentation for Grails 3?

### ISSUE THREAD

**Issue by fedotxxl** [bertramdev/grails-asset-pipeline#264]

**Comment by phidias51** [comment]
That would be really useful.  The documentation refers to configuration files that don't work.  There is configuration information in **build.gradle** and **application.groovy**, and setting the values there seems to have no impact on the amount of processing that the asset pipeline does.

**Comment by davydotcom** [comment]
New Docs!

http://www.asset-pipeline.com/manual/#grails3
