### ISSUE TITLE
Cannot turn off JS minification or change optimizationLevel when fixtures plugin is installed

### ISSUE THREAD

**Issue by jako512** [bertramdev/grails-asset-pipeline#281]
When fixtures plugin is installed the following configuration has no effect on minification - SIMPLE method is used anyway:
`grails.assets.minifyOptions.optimizationLevel = 'WHITESPACE_ONLY'`

Also when I try to turn off minificaiton completely (`grails.assets.minifyJs = false`), the minification is performed...

Exact steps to reproduce the problem:
- create new Grails 2.5.0 app
- add fixtures plugin to *BuildConfig.groovy*: `        compile ":fixtures:1.3"`
- turn off JS minification in *Config.groovy*: `grails.assets.minifyJs = false`
- create war: `grails war`
- check that *target/assets/application.js* is correctly **unminified**
- clean: `grails clean`
- create war again: `grails war`
- check that *target/assets/application.js* is incorrectly **minified**
- delete *target/work/plugins/fixtures-1.3*
- clean: `grails clean`
- create war again: `grails war`
- check that *target/assets/application.js* is correctly **unminified**
- clean: `grails clean`
- create war again: `grails war`
- check that *target/assets/application.js* is incorrectly **minified**

**Comment by jako512** [comment]
After deleting grails work dir it works as expected but only once - running `grails war` command second time without deleting work dir causes full minification of js files

**Comment by davydotcom** [comment]
this plugin is super old. are you sure this is even related to asset-pipeline?

**Comment by davydotcom** [comment]
was unable to reproduce with asset pipeline version 2.6.10

**Comment by jako512** [comment]
I can still reproduce the problem even when changed asset-pipeline version from 2.1.5 to 2.6.10.
Just look at *target/assets/application-837d5979e4ef3797bbaa42629ea278e3.js* instead of *target/assets/application.js*

**Comment by animator013** [comment]
I am suffering from the exact same problem. I was also able to reproduce this issue with the steps provided.
