### ISSUE TITLE
Handling minification of third-party assets

### ISSUE THREAD

**Issue by rgoldberg** [bertramdev/grails-asset-pipeline#284]
Sometimes, the Google Closure Compiler causes problems when it minifies js assets.  Other minifiers might also cause issues for other asset types.

For simplicity, everything below only mentions js assets, but the same principles also apply for other minifiable asset types, like css.

If I want to serve a third-party js asset, I don't want to edit the code of that asset to make it compatible with Closure.

There are many feasible ways to handle this situation.

For brevity, I will only present what I imagine would be the best solution, though there are other solutions.

It would be good to be able to:

1. disable minification for specific assets, using the new `grails.assets.minify.js.exclude` setting in `Config.groovy`, which can either be:
  1. a `String` regex for which any matching asset path will not be minified
  2. a `Collection<String>` (where each element is a regex) for which any asset path that matches any element regex will not be minified
  3. a `Closure<Boolean>` that accepts a single `File` argument that is for the asset path.  If the `Closure` returns a true value, then the file will be minified; otherwise, it won't be minified
  4. a `java.util.regex.Pattern` for which any matching asset path will not be minified
  5. a `Collection<java.util.regex.Pattern>` for which any asset path that matches any element `Pattern` will not be minified

2. use a pre-minified version of the third-party library instead of the non-minified version, and instead of Asset Pipeline minifying the non-minified version.  The following rules would only apply if `grails.assets.minifyJs == true`:
  1. if `x.js` (a non-pre-minified asset) exists, but `x.min.js` doesn't, then `x.js` served non-minified from `x.unminified.js`, and served minified (by Google Closure Compiler called by Asset Pipeline) from `x.js` (same as current behavior)
  2. if `x.min.js` (a pre-minified asset) exists, but `x.js` doesn't exist, then the pre-minified asset will not be minified by Asset Pipeline (same as current behavior), and it will be served from both `x.js` (new behavior) & `x.min.js` (same as current behavior)
  3. if both `x.js` (a non-pre-minified asset) and `x.min.js` (a pre-minified version of the `x.js` asset) exist, then neither file will be minified by Asset Pipeline.  The pre-minified asset (originally from `x.min.js`) will be served from both `x.js` and `x.min.js`, whereas the non-minified asset (originally from `x.js`) will be served from `x.unminified.js`
  4. I'll look into `.map` files to determine if their URLs must be changed at all

When `precompiled == false`, remapping of assets & their minified versions to different URLs can be handled by the `AssetPipelineFilter`

When `precompiled == true`, remapping of assets & their minified versions to different URLs will have been handled by the asset compiler changing the names of the appropriate asset files that it writes to the `assets` directory and its subdirectories.

**Comment by davydotcom** [comment]
Can go more into this later but you do NOT want to use existing precompiled assets. Precompiling really only works well on a final bundle because all the local vars change. I actually haven’t seen a case where Closure causes problems either. Ive used it with Jquery, D3js, c3, nvd3, extjs, and prototype.

**Comment by rgoldberg** [comment]
I haven't yet used bundles since I'm upgrading an existing application.  I'll look into bundles in the future, and, if the same minification / compilation problem exists for AngularJS in bundles, then I'll let you know.

Thanks for the info.

**Comment by ctoestreich** [comment]
I have, in the past, thought about this feature as well.  A few cases where using the non-minified version of a 3rd party script could be an issue.

* The 3rd party min version is the combination of several fines for convenience.  This is pretty common with modern js build stacks
* A lot of time a energy has been spent to automatically or manually reduce file size that might not be achieved by the standard asset-pipeline minification.  Several libraries tout their compression as optimal and in some cases it is true and matter
* Some minified scripts have been hyper obfuscated in an attempt to make them more secure.  This is also an emerging technology offering

Overall I think having the ability to opt out of a minify/obfuscate cycle for a script in the assets dir would be a nice feature.

**Comment by davydotcom** [comment]
just need to figure out a minify exclude pattern

**Comment by ctoestreich** [comment]
I think mini fixation and bundling are different issues... I think the using a garils.assets.minification.excludes list or something of that nature. There could also be a similar lost for bundle exclude but that seems unnecessary.

**Comment by ctoestreich** [comment]
Wow autocorrect minification not mini fixation.

**Comment by davydotcom** [comment]
`minifyOptions.excludes = []` patterns will be excepted in next release

**Comment by davydotcom** [comment]
added to 2.8.0 and 3.2.0

**Comment by amcclain** [comment]
Thanks for this! We are eager to try it, as we had issues with double-minification and ExtJS (weirdly enough only with some browsers, notably Firefox). Appreciate the additional control here. 👍

**Comment by davydotcom** [comment]
np just a heads up i had to bump gradle plugin to 2.8.1 if using grails3 whoops, everything else is good togo
