### ISSUE TITLE
Have to physically delete .asscache file to get AngularJS Template AP setting changes to take effect

### ISSUE THREAD

**Issue by scrain** [bertramdev/grails-asset-pipeline#288]
Using Grails 2.4.5, Asset Pipeline 2.5.1 and AngularJS Template AP 2.2.1, once the application has been ran and the asset cache loaded, changes to the config setting `grails.assets.angular.includePathInName` have no effect, unless the cache file is deleted between runs.  

Sample application [here](https://github.com/scrain/AngularTemplateIssue)

See [comment in config.groovy](https://github.com/scrain/AngularTemplateIssue/blob/master/grails-app/conf/Config.groovy#L124) on how to reproduce.

Hopefully you're not going to tell me to take this issue to the AngularJS Template AP project... :-)

**Comment by davydotcom** [comment]
need to add config digest to expire cache on change of digest

**Comment by davydotcom** [comment]
config is now digested for next release
