### ISSUE TITLE
War creation succeeding despite severe uglify errors

### ISSUE THREAD

**Issue by kevana** [bertramdev/grails-asset-pipeline#296]
I noticed that when I use ES6 features the Closure Compiler throws errors as expected because the default languageMode is ES5, but WAR creation succeeds and the resulting file is empty.

```
grails war
. . . <omitted>
Sep 24, 2015 9:53:26 AM com.google.javascript.jscomp.LoggerErrorManager println
SEVERE: bsb.unminified.js:24: ERROR - this language feature is only supported in es6 mode: let declarations. Use --language_in=ECMASCRIPT6 or ECMASCRIPT6_STRICT to enable ES6 features.
        let deviceSizesMap = new Map();
            ^
. . . <omitted>
Sep 24, 2015 9:53:26 AM com.google.javascript.jscomp.LoggerErrorManager printSummary
WARNING: 6 error(s), 0 warning(s)
|Processing File 224 of 540 - bsb.js
|Uglifying File 224 of 540 - bsb
|Compressing File 224 of 540 - bsb
. . . <omitted>
|Finished Precompiling Assets
....
|Done creating WAR target/projectName-0.1.war

Process finished with exit code 0
```

And the file contents in the WAR only has the source map URL but no content.
```
//# sourceMappingURL=bsb.js.map
```

I'd like war creation to fail on any error, am I missing a setting for this?

**Comment by davydotcom** [comment]
you can force closure to use ES6 language mode 

```
minifyOptions = [languageMode: 'ES6', targetLanguageMode: 'ES6']
```

**Comment by kevana** [comment]
Yes, that's what we're doing now. My concern is that errors encountered in the closure compiler don't seem to fail the build. It prints the error in the log, but a WAR is still created with an empty JS file and the process exits with code 0. I would expect for the entire build to fail when an error like this happens.

**Comment by davydotcom** [comment]
Thats a great point . Let me look into why its not failing the build

**Comment by davydotcom** [comment]
ah this is a bug its supposed to continue but skip the minify and leave original contents

**Comment by kevana** [comment]
Was this fixed?

**Comment by davydotcom** [comment]
I believe it was it succeeds just doesn't Minify and keeps original source

**Comment by sachinanand** [comment]
I think I am running into this issue with my spring boot app too, where I am trying to make my front end in react.js

**Comment by sachinanand** [comment]
Ok. I got it from here.

https://github.com/bertramdev/asset-pipeline
