### ISSUE TITLE
Place the default cache file in target folder of grails

### ISSUE THREAD

**Issue by bond-** [bertramdev/grails-asset-pipeline#301]
I'm using a version control system and the cache file ".asscache" shows up as uncommitted changes. It would be good if this can be placed in target folder since this is a generated file.

Currently I just used .gitignore file to ignore it.

**Comment by davydotcom** [comment]
party pooper ;)

**Comment by davydotcom** [comment]
this actually requires a core change as thsi file is framework agnostic. Ill have to make its location configurable

**Comment by davydotcom** [comment]
core now supports this with `AssetPipelineConfigHolder.config.cacheLocation`
