### ISSUE TITLE
asset.excludes still minifies excluded directory's files

### ISSUE THREAD

**Issue by ocomsoft** [bertramdev/grails-asset-pipeline#311]
I have the following 
```java
grails.assets.excludes = ["bower_components"]
```
in my config.groovy because the minifier struggles to process all the files in there.

However the plugin is still processing all the files in this directory. Even ones NOT require d in assets because no asset are required from this folder. I use bower-installer to copy them. 

Using plugin Version 2.5.7

**Comment by davydotcom** [comment]
You need to use a glob pattern not simply a folder

bower_components/**/*

**Comment by ocomsoft** [comment]
Thanks. That Works. 

However if would be much easier when the file cannot be minified that it's just included as is instead of crashing so we don't have to work around it.
