### ISSUE TITLE
assets excludes for build.gradle

### ISSUE THREAD

**Issue by genuinefafa** [bertramdev/grails-asset-pipeline#313]
I'm using Grails 3.0.8; with `build.gradle` setup like this:
```groovy
assets {
// ...
    excludes = ['mixins/*.scss', 'tiny_mce/src/*.js', '**/**/*.spec.js']
// or
    excludes = ['mixins/*.scss', 'tiny_mce/src/*.js', '**/*.spec.js']
}
```

But I'm still getting, while developing, errors like: `yeoman.controller.spec.js?compile=false:2 Uncaught ReferenceError: describe is not defined` because a wrote `//= require_tree .` on parent directory for the `spec.js` file.

What am I doing wrong?

ps: I thought I wrote this issue before but I cannot find it anymore.

**Comment by genuinefafa** [comment]
Duplicated #303

**Comment by davydotcom** [comment]
Excludes do not effect require patterns they effect post processed asset inclusion. Try moving your test specs into a separate folder like grails-app/assets/test/specs
