### ISSUE TITLE
Asset pipeline does not work well with Grails pathing JAR solutions

### ISSUE THREAD

**Issue by gregopet** [bertramdev/grails-asset-pipeline#314]
This isn't a bug report per se as the Asset Pipeline does nothing wrong AFAIK, but more of a question and a polite request for suggestions.

Some of our Windows developers have hit the 'File name too long' bug when developing Grails applications and after some time we've managed to come to a working pathing JAR solution solution based on [this](https://github.com/grails/grails-core/issues/9300) bug report - a proper solution seems to be nowhere in sight (last time I checked Gradle and Grails couldn't agree on whose responsibility it was to fix this).

Anyhow, while the app now works for us the asset pipeline has stopped working in development mode: the assets are served minified (which we can turn off) and bundled (which we can't turn off) and if I remember correctly, the app has to be restarted for any changes to show. Is there anything we could try to switch it back again?

Below is what we've had to add to `build.gradle` to get the build running on Windows - now we can run `gradle bootRun` to get a working application on Windows machines. We've tried modifying the `run` task instead, without improvement.

```groovy
task launcherJar(type: Jar) {
    def gradleUserHome = new File(gradle.getGradleUserHomeDir(), "caches")

    def relativeClasspathEntries = configurations.runtime.files.collect {
        new File(gradleUserHome.getAbsolutePath()).toURI().
                relativize(new File(it.getAbsolutePath()).toURI()).getPath()
    }
    appendix = "launcher"
    destinationDir = gradleUserHome
    doFirst {
        manifest {
            attributes "Class-Path": relativeClasspathEntries.join(" ")
        }
    }
}

compileGroovy{
  dependsOn launcherJar
    FileCollection collection = files(launcherJar.archivePath);
    def finCollection = collection
    doLast {
        classpath = finCollection
    }
}

bootRun{
    doFirst{
        //The main build directories aren't collected so they are added manually
        FileCollection collection = files("${project.rootDir}/build/classes/main") + files("${project.rootDir}/build/resources/main") + files(launcherJar.archivePath)
        println collection.files
        classpath = collection
    }
}
```

**Comment by lhigginbotham** [comment]
:+1:
I'm also interested in any information about this.  We're trying to move towards the asset-pipeline plugin as part of our migration to 3.0.x and I'm seeing this issue.

**Comment by davydotcom** [comment]
So just to clarify, we are talking about a mod with asset-pipeline to bypass an underlying issue with either grails or gradle?

**Comment by lhigginbotham** [comment]
I think more like a mod to an application to bypass an underlying issue with grails or gradle causing certain functionality in asset-pipeline to not function correctly.

Essentially, in a Windows environment, there is a point where too many dependencies in build.gradle prevents compilation because the classpath gets too long for Windows command line to handle.  What the above code does is collect the dependencies and dump them into a single jar to work around that limit.  That jar is what is put in the classpath instead.  This seems to cause the above behavior.

Any idea why the change would effect asset-pipeline?

**Comment by gregopet** [comment]
We've managed to get around the problem: the trick is to remove any existing assets and stop asset precompilation when creating the pathing jar which can all be fitted into a single gradle command: `gradle assetClean run -x assetCompile`

If assets aren't included in the JARs, the pipeline will compile them on the fly as usual. If somebody knows off the top of their head how to include this into the build file we could produce a canonical solution to Windows long path name problem :)

**Comment by libinlong** [comment]
from the following post, someone suggested to add "exclude { it.file.absolutePath.contains('assetCompile') }" to your launchingJar definition. 
https://github.com/grails/grails-core/issues/9125

They seems to put the fix in later version of grails, but i tried version 3.0.15, it doesn't solve the asset pipeline issue, maybe a newer version might work.
