### ISSUE TITLE
Grails 3 asset mapping config being ignored from plugin

### ISSUE THREAD

**Issue by ctoestreich** [bertramdev/grails-asset-pipeline#317]
It would appear that setting the following in a plugin's config does not get picked up from an application.  You have to directly add this to your application level config.  Other non-asset-pipeline config properties are read just fine from the plugin's `application.yml`

```
grails:
    assets:
        mapping: foo-assets
```

**Comment by ctoestreich** [comment]
Tried adding 

`def loadBefore = ['asset-pipeline', 'assetPipeline']` to the plugin to no avail.

**Comment by davydotcom** [comment]
This would be a Grails bug

**Comment by ctoestreich** [comment]
Maybe. I just sent off a pull request for plugin environment mapping and got familiar with this code. I didn't see anything that wilt cause this behavior. I also didn't see anything specific in the asset pipeline plugin that would cause this either. Will debug in more detail and update.

**Comment by ctoestreich** [comment]
Turns out that when a plugin is stand alone it needs an application.yml.  When it is consumed it needs a plugin.yml.  Asset pipeline properties need to be in the plugin.yml to be consumed by applications that use the plugin.
