### ISSUE TITLE
Plugin assets conflicting with one another & with application assets

### ISSUE THREAD

**Issue by rgoldberg** [bertramdev/grails-asset-pipeline#319]
From reading the documentation, it seems like assets with the same path from more than one plugin (or from one or more plugins and the application itself) can conflict.

This also means that as an AP user, I need to know all assets (and plugins `web-app` files, too) to ensure no conflicts / rearrange.  This doesn't seem safe or scalable.  What if two different third-party plugins need totally different assets under the same path?  Is it possible to resolve the conflict without modifying one or both plugins?

I saw the `grails.assets.plugin.*.excludes` setting, but if I exclude a plugin's assets, will the plugin fail if it needs the excluded assets, and I don't provide an override?  (I assume so)

Wouldn't it be better to serve plugin assets from a separate base path from app assets, and have a separate directory for each plugin?  So, if my app used plugins a & b, and both of them, and my app, all had an asset named x.js, the paths would be:

    /plugin-assets/a/x.js
    /plugin-assets/b/x.js
    /assets/x.js

`/plugin-assets/` would be configurable, just like the `mapping` setting can change `/assets/`.

If any app or plugin specifically wanted to override an asset from another plugin, e.g. my app overrides x.js from plugin a, then it could place the overriding asset in:

    /grails-app/plugin-assets/a/x.js

This would prevent asset path conflicts, yet still allow overriding.

If you want to simultaneously support the current behavior along with the new behavior, you could have a boolean that switches between them, and that defaults to the current behavior.  After a long time, and many warnings, you could eventually switch the default over to the new behavior.

**Comment by davydotcom** [comment]
It's more appropriate for plugins to nest their files in plugin named folders. It's treated like a layered file system similar to how docker works, allowing the main app to even override plugin provided assets if necessary . This is by design and totally scalable. I've seen 3000+ asset plugin based projects experience no problems

**Comment by rgoldberg** [comment]
The problem is that this setup expects plugin writers to write proper code.

You should enforce no bugs, instead of relying on others to not make mistakes.

**Comment by davydotcom** [comment]
I expect plugin writers to follow the convention put forth by the asset pipeline. And allow user override this concept is not foreign it's the same in rails asset pipeline and has worked very well for them.  Also Merry Christmas
