### ISSUE TITLE
Encoding issues

### ISSUE THREAD

**Issue by damirarh** [bertramdev/grails-asset-pipeline#322]
When building on Windows I am encountering encoding issues with JavaScript files being processed by the pipeline. Here's how I am able to reproduce it:

- Create a new Grails app: `grails create-app encoding`
- Add a new file (`encoding.js`) to `grails-app\assets\javascripts` with the following contents:

```
var slovenian = 'čšžČŠŽ';
var russian = 'чшжЧШЖ';
```

- Process the assets: `gradle assetCompile`
- Check the files in `build\assetCompile\assets`:
   - Unminified file (`application.unminified.js`) is recognized as ANSI encoded but contains unmodifed Unicode characters which can be read correctly if the file is treated as UTF-8:
   ```
   var slovenian = 'ÄÅ¡Å¾ÄŒÅ Å½';
   var russian = 'Ñ‡Ñ?Ð¶Ð§Ð¨Ð–';
   ```
   - Minified file (`application.js`) has all the Unicode characters encoded as their 2-byte UTF-8 representation:
   ```
   var slovenian="\u00c4\u0164\u0139\u02c7\u0139\u013e\u00c4\u015a\u0139\u00a0\u0139\u02dd",russian="\u0143\u2021\u0143\ufffd\u0110\u00b6\u0110\u00a7\u0110\u00a8\u0110\u2013";
   ```

According to [documentation](http://bertramdev.github.io/grails-asset-pipeline/guide/usage.html#encoding) encoding should be specified in the manifest file, therefore I added the following at the top of `application.js`:

```
//= encoding UTF-8
```

Now the minified file (`application.js`) is generated correctly:

```
var slovenian="\u010d\u0161\u017e\u010c\u0160\u017d",russian="\u0447\u0448\u0436\u0427\u0428\u0416";
```

The unminified file (`application.unminified.js`) is completely stripped of Unicode characters:

```
var slovenian = 'èšžÈŠŽ';
var russian = '??????';
```

I think that the generated unminified file doesn't correctly handle the encoding specified in the manifest file.

I attached the original `encoding.js` file and the generated `application.js` and `application.unminified.js` files in both cases: with no encoding set and with UTF-8 encoding set.

[original.zip](https://github.com/bertramdev/grails-asset-pipeline/files/75476/original.zip)
[generated-noencoding.zip](https://github.com/bertramdev/grails-asset-pipeline/files/75475/generated-noencoding.zip)
[generated-utf8.zip](https://github.com/bertramdev/grails-asset-pipeline/files/75477/generated-utf8.zip)

**Comment by davydotcom** [comment]
Did you specify charger when requesting the file?

**Comment by damirarh** [comment]
Charger?

**Comment by davydotcom** [comment]
Autocorrect charset

**Comment by damirarh** [comment]
You mean adding `charset`  to the asset reference in the view like this?

    <asset:javascript src="application.js" charset="utf-8"/>

I tried it now and as expected, it didn't make any difference. When I described the problem above, I was looking at the files in the file system, hence before they were sent to the browser.

But the behavior in the browser is as follows:

- In the `development` environment (i.e. when I started the app with `grails run-app`) when the asset file aren't processed, I have no encoding issues either with or without the charset specified.
- In the `production` environment (i.e. when I do `grails package` and then start it with `java -jar .\build\libs\encoding-0.1.jar`) when the processed asset files are served, the browser receives them as they are generated in the file system and described above - if I set the encoding in the manifest file, the minified file that browser uses is ok and working correctly, but the unminified file that's shown in the browser debugger through source mapping has `?` in place of Unicode characters.

**Comment by davydotcom** [comment]
Try -Dfile.encoding=UTF-8 I'll look into why this is but that will force default encoding for jvm

**Comment by damirarh** [comment]
Yes, invoking `gradle -D"file.encoding=UTF-8" assetCompile` does the trick. Both with and without specifying encoding in the manifest file the generated files keep correct encoding (minified and unminified). This seems to be the same behavior as with another developer on the team who uses Linux. Thank you for the suggestion.
