### ISSUE TITLE
Returning HTTP 500 for assets after a while

### ISSUE THREAD

**Issue by rlovtangen** [bertramdev/grails-asset-pipeline#323]
We have an application that has been running for weeks, that suddenly will not server assets. Instead it responds with HTTP 500 and the standard Grails error.gsp.
This is second time this happens to our application. Last time the problem resolved itself after a while.
I can't find any exception in the logs.

![screen shot 2016-01-04 at 17 22 13](https://cloud.githubusercontent.com/assets/233839/12094248/d7008718-b307-11e5-8f77-5800b6c02177.png)

asset-pipeline 2.6.0, sass-asset-pipeline:2.6.0, less-asset-pipeline:2.6.0, asset-autoprefixer:1.3.0
Grails 2.5.0

**Comment by rlovtangen** [comment]
The file is actually in the war-file:
````
assets$ ls -l |grep spinner
-rw-rw-r-- 1 tomcat tomcat    2037 Jan  4 13:50 spinner-c7b3cbb3ec8249a7121b722cdd76b870.gif
````

**Comment by davydotcom** [comment]
What version of asset pipeline?

**Comment by rlovtangen** [comment]
asset-pipeline 2.6.0
sass-asset-pipeline:2.6.0
less-asset-pipeline:2.6.0
asset-autoprefixer:1.3.0
Grails 2.5.0

I talked to a guy at the slack channel which had experienced the same problem. They solved it by downgrading to asset-pipeline 1.9.4.

**Comment by rlovtangen** [comment]
Now, after a few hours, the application is back on track again.
 
![screen shot 2016-01-05 at 09 03 53](https://cloud.githubusercontent.com/assets/233839/12110321/63a899f2-b38b-11e5-93ab-d4e03534f250.png)

**Comment by davydotcom** [comment]
I'd try a more recent version 2.6.0 is old I believe this was solved

**Comment by davydotcom** [comment]
Asset pipeline 1.9.4 is very old and much more inefficient. I'd try 2.6.10

**Comment by rlovtangen** [comment]
Ok, we're already running 2.6.10 in production, so hopefully we won't run into this problem again.

**Comment by davydotcom** [comment]
The only thing i could think of it being was the thread safety issue that
was resolved or the resource reference cache. I doubt the latter so i bet
your good.

**Comment by rlovtangen** [comment]
Hope so, thanks.

**Comment by blazewiczp** [comment]
I did experience the same error with version 2.5.9. As a quick fix, I upgraded to the latest, 2.9.10 version. I hope it will fix the issue.

**Comment by davydotcom** [comment]
It will this was a data concurrency hash map issue in the attribute cache
in 2.5.x line

**Comment by blazewiczp** [comment]
Good to know, thanks for the update David.
