### ISSUE TITLE
require_tree not working from a plugin

### ISSUE THREAD

**Issue by jamescookie** [bertramdev/grails-asset-pipeline#324]
In a grails plugin, when I have

    //= require_tree .

(or require_tree [anyfolder]) the assets in that folder are not included. I can included them all individually, but I have a requirement to exclude some based on configuration.

**Comment by davydotcom** [comment]
To clarify this is Grails 2 or 3?

**Comment by jamescookie** [comment]
Grails 3

**Comment by davydotcom** [comment]
this is with regards to binary plugins. will have to be fixed in grails plugin.

**Comment by davydotcom** [comment]
this will work in next release with exploded plugins or plugins that have a project directory reference

**Comment by davydotcom** [comment]
fixed in 2.8.0 / 3.2.0

**Comment by davydotcom** [comment]
to use you do need to add asset-pipeline-gradle to your plugin build.gradle

then add 

```
assets {
 packagePlugin = true
}
```
