### ISSUE TITLE
auth:1 Uncaught SyntaxError: Unexpected token <

### ISSUE THREAD

**Issue by VenelinPetkov** [bertramdev/grails-asset-pipeline#325]
Grails 3.1.0RC1

**Comment by davydotcom** [comment]
reopen with more details

**Comment by mexx91** [comment]
Same problem here. In my case it seems to be some issue with the asset-pipeline plugin. Intellij says in auth.gsp at the line "<asset:javascript src="jquery-2.2.0.min.js"/>": "Element asset:javascript is not allowed here."
It wasn't a problem before I changed some config of spring-security. But maybe it is coincidence.

In my build.gradle I tried "runtime "org.grails.plugins:asset-pipeline:3.0.1" and also version 3.0.15. Both failed.
