### ISSUE TITLE
Can't separate the files in custom environment

### ISSUE THREAD

**Issue by YueZhaoDreams** [bertramdev/grails-asset-pipeline#327]
I have a custom environment "local" to do debugging and development.
I know in dev environment, the javascript files are separate. I try to achieve it in "local" environment. 

In my "local" environment config, I tried 
```groovy
grails.assets.bundle = false
```
 and
```groovy
grails.assets.bundle = false
grails.assets.allowDebugParam = true
```

But it doesn't work.

**Comment by davydotcom** [comment]
what grails version and are you using run-app… also the examples are missing .

`grails.assets.bundle = false`

**Comment by YueZhaoDreams** [comment]
I'm using -Dgrails.env=local run-app. The Grails is 2.3.11.
Below is my local_config.groovy which is an externalized config file.
```groovy
environments{
	local{
                grails.assets.bundle = false
		grails.assets.allowDebugParam = true
	}
}
```

below is my gsp:
```html
<html>
<head>
<asset:stylesheet href="financial.css" />
<asset:javascript src="financial.js" />
...
</head>
</html>
```

below is my financial.js:
```javascript
//= require common.js
//= require jszip.js
//= require xlsx.js
//= require handsontable.full.min.js
...
//some javascript code
```

**Comment by davydotcom** [comment]
your running areally old version. This has been resolved in newer versions of asset-pipeline (2.x series)
