### ISSUE TITLE
No link to asset with dots in filename

### ISSUE THREAD

**Issue by urbansky** [bertramdev/grails-asset-pipeline#329]
My environment: Grails 2.4.3 in development mode

`<asset:javascript src="jquery-ui/jquery.ui.datepicker-de"/>`
The link to the asset will not be rendered.

And if I rename the asset file (replace the dots):
`<asset:javascript src="jquery-ui/jquery-ui-datepicker-de"/>`
The link will be rendered.

Are there any problems with dots in asset filenames?

**Comment by davydotcom** [comment]
yea you need to add `.js` to the end if your using dots
