### ISSUE TITLE
Url rewrite does not work for assets inherited from plugin

### ISSUE THREAD

**Issue by pawelhalasa** [bertramdev/grails-asset-pipeline#334]
Replication steps (tested with Grails 3.1.4)

1. Create a new Grails plugin and copy font-awesome folders into grails-app/assets/vendor
2. Create a new Grails app and add the following line to application.css:
`*= require font-awesome/css/font-awesome.css`
3. Add inline plugin dependency to your app (as described in [Grails user guide](http://grails.github.io/grails-doc/3.1.x/guide/plugins.html))
4. Create application WAR file

Result: In build output files font-awesome.css is included to application.css, but all url entries from font-awesome.css are unchanged (thus not pointing to correct font files), e.g.

```
@font-face {
  font-family: 'Glyphicons Halflings';
  src: url('../fonts/glyphicons-halflings-regular.eot');
  ...
```

should be changed to: 
```
@font-face {
  font-family: 'Glyphicons Halflings';
  src: url('font-awesome/fonts/glyphicons-halflings-regular.eot');
  ...
```

**Comment by davydotcom** [comment]
should work now
