### ISSUE TITLE
3.1.3 Cannot get resource with only dir (3.0.15 last known working version for me)

### ISSUE THREAD

**Issue by AlexKovynev** [bertramdev/grails-asset-pipeline#337]
resource(dir:'js')

AssetProcessorService.groovy

String url = getResolvedAssetPath(attrs.file ?: attrs.src)

then trimLeadingSlash(path)

and Null Exception

**Comment by davydotcom** [comment]
what exactly are you expecting as the output from this since you are not specifying a target file

**Comment by AlexKovynev** [comment]
https://grails.github.io/grails-doc/latest/ref/Tags/resource.html
As you can see all params is optional. So resource(dir:'js') must be acceptable, and is was, in version 3.0.15

**Comment by davydotcom** [comment]
More details on this. The assumed issue has nothing to do with trimLeadingSlash it has to do with a manifest.getProperty(). before diagnosing make sure you compare the stack trace against the source file from the appropriate version tag not master or grails3 branch. This has been resolved for 3.1.4 release which should happen either tonight or tomorrow morning
