### ISSUE TITLE
Cannot cast object '[Digest Input Stream] MD5 Message Digest from SUN

### ISSUE THREAD

**Issue by rodriguezkatarina** [bertramdev/grails-asset-pipeline#340]
Why am I getting this error when running `grails war`?
I'm using `asset-pipeline:2.7.4`  on `grails 2.4.5`.
It used to work for `asset-pipeline:1.9.9` but upgrading seems to break it.
```
| Processing File 452 of 1527 - app/manifest.js.
| Error WAR packaging error: Cannot cast object '[Digest Input Stream] MD5 Message Digest from SUN, <initialized>
' with class 'java.security.DigestInputStream' to class 'java.io.ByteArrayInputStream'
```

This is what my manifest.js looks like:
```
//= require scripts/scripts.js
//= require app/app.module.js

//= require app/blocks/logger/logger.module.js
//= require app/blocks/logger/logger.js

.... other requires here...
```

scripts.js is another one that look like this:
```
//= require jquery-2.1.3/jquery-2.1.3.min.js
//= require jquery-2.1.3/jquery.price_format.2.0.min.js
//= require jquery-ui-1.10.4/ui/minified/jquery-ui.min.js
//= require jquery-ui-1.10.4/ui/minified/jquery.ui.datepicker.min.js
//= require jquery-ui-1.10.4/ui/jquery.ui.timepicker-addon.js

--- other requires here ---
```

**Comment by PiotrZakrzewski** [comment]
Hi I am also having the very same issue. Would you mind sharing why this issue was closed? Is it fixed in some version?

**Comment by davydotcom** [comment]
Try doing a clean as we can't get it to happen

**Comment by PiotrZakrzewski** [comment]
The issue persists after clean as well. It is hard to figure out what is causing it - it fails on (the same in the original issue by @rodriguezkatarina ) on manifest files (with //= require )
Mine looks like this:
 
   /**
    * Original
    * File: AdminResources
    * Module: adminTab
    */

    //= require jquery
    //= require extjs
    //= require session_time.js
    //= require usergroup.js
    //= require utilitiesMenu.js

**Comment by davydotcom** [comment]
What grails version by chance? It almost seems as if Groovy CompileStatic is messing up

**Comment by davydotcom** [comment]
Oh @PiotrZakrzewski send me your build.gradle or BuildConfig

**Comment by PiotrZakrzewski** [comment]
The build file https://github.com/thehyve/transmart-upgrade/blob/master/transmartApp/build.gradle
Grails version is 3.1.10 with Groovy Version: 2.4.7 and JVM Version: 1.8.0_45

**Comment by davydotcom** [comment]
I'd bump your dependency version your build cradle indicates you are running 2.8.2

**Comment by PiotrZakrzewski** [comment]
Hi Davy, 

Thanks for suggestion - i bumped it to com.bertramlabs.plugins:asset-pipeline-gradle:2.11.1
but I still get the same error. Do you have an idea how can I workaround this issue?

**Comment by PiotrZakrzewski** [comment]
I have found out the issue - what is causing this bizarre error is a reference to a nonexistent .js file. It would be great if this case was covered and error reported was e.g. "file x.js does not exist"

**Comment by doracl** [comment]
I also got the same error,when used the fullPage(https://github.com/alvarotrigo/fullPage.js) in grails plugin

**Comment by davydotcom** [comment]
Upgrade to latest
