### ISSUE TITLE
Cannot cast object '[Digest Input Stream] MD5 Message Digest from SUN

### ISSUE THREAD

**Issue by rodriguezkatarina** [bertramdev/grails-asset-pipeline#341]
Why am I getting this error when running `grails war`?
I'm using `asset-pipeline:2.7.4`  on `grails 2.4.5`.
```
| Processing File 452 of 1527 - app/manifest.js.
| Error WAR packaging error: Cannot cast object '[Digest Input Stream] MD5 Message Digest from SUN, <initialized>
' with class 'java.security.DigestInputStream' to class 'java.io.ByteArrayInputStream'
```

This is what my manifest.js looks like:
```
//= require scripts/scripts.js
//= require app/app.module.js

//= require app/blocks/logger/logger.module.js
//= require app/blocks/logger/logger.js

.... other requires here...
```

scripts.js is another one that look like this:
```
//= require jquery-2.1.3/jquery-2.1.3.min.js
//= require jquery-2.1.3/jquery.price_format.2.0.min.js
//= require jquery-ui-1.10.4/ui/minified/jquery-ui.min.js
//= require jquery-ui-1.10.4/ui/minified/jquery.ui.datepicker.min.js
//= require jquery-ui-1.10.4/ui/jquery.ui.timepicker-addon.js

--- other requires here ---
```

**Comment by rodriguezkatarina** [comment]
NVM. I just realized somebody added a `.map` file in scripts.js.
It ran fine when I removed it. The browsers console complained though. Not sure where I could put .map files.

**Comment by davydotcom** [comment]
how was the map defined in the file?

**Comment by rodriguezkatarina** [comment]
Same as the others.
```
 //= require ZeroClipboard/2.2.0/ZeroClipboard.min.js
//= require ZeroClipboard/2.2.0/ZeroClipboard.min.map
```

Is there a different syntax for including `.map` files? Should I include it? Or is it ok to omit? *sorry about the noob question*

**Comment by davydotcom** [comment]
A map is just a way to look at non minified data. You really don’t even need to bother using a minified library here since when you do package for final war the entire bundle is minified as a single set.

the min.js file itself will have a comment at the top referencing a map you should never bundle a map into your require directives.

**Comment by rodriguezkatarina** [comment]
Thanks. :dancer:
