### ISSUE TITLE
No such property: assetPipelinePluginDir for class: _Events (during test-app)

### ISSUE THREAD

**Issue by dynamind** [bertramdev/grails-asset-pipeline#89]
I have created a fresh Grails 2.3.7 project and included the latest version of asset-pipeline (1.8.1), by adding the following line to `BuildConfig.groovy`:

```
compile ":asset-pipeline:1.8.1"
```

When I run `grails test-app` I get the following error:

```
Error loading event script from file [/my-local-plugin-path/asset-pipeline/scripts/_Events.groovy] 
No such property: assetPipelinePluginDir for class: _Events
```

It appears that during execution of `test-app`, the file `_Events.groovy` is evaluated twice; the first time the variable `assetPipelinePluginDir` variable is available, but not the second time.

The problem appears to be this line, which is included for the `eventCreateWarStart` event. 

``` groovy
includeTargets << new File(assetPipelinePluginDir, "scripts/_AssetCompile.groovy")
```

I tried getting the value of `assetPipelinePluginDir` by inserting the following code above it:

``` groovy
import org.codehaus.groovy.grails.plugins.GrailsPluginUtils
def assetPipelinePluginDir = GrailsPluginUtils.pluginInfos.find { it.name == 'asset-pipeline' }.pluginDir.toString()
```

But then other stuff starts to break:

```
Error loading event script from file [/my-local-plugin-path/asset-pipeline/scripts/_Events.groovy] 
No such property: projectCompiler for class: _PackagePlugins
```

Moving the `includeTargets` command inside the `eventCreateWarStart` closure appears to fix the problem, but I'm not sure that's the proper way.

Should this be fixed in Grails or in Asset Pipeline? I haven't been able to find any other reports concerning this issue, but I've started to investigate due to failing Jenkins jobs.

**Comment by namaggarwal** [comment]
Hi,

Why was this issue closed? I am still getting that error and its independent of version, I have tried 1.9.9, 1.8.3 and 1.7.1

**Comment by davydotcom** [comment]
Have you tried 2.5.1?

**Comment by namaggarwal** [comment]
Hi,

The error is same when I try 2.5.1 . I guess there is some other plugin interfering with this as it works fine when I create a new project.
